#! /bin/sh

bspc monitor HDMI-1 -d '' '' '' '' '' '' '' ''
bspc monitor eDP-1 -d '' '' '' '' '' '' '' ''

bspc config border_width 2
bspc config window_gap 13

# source the colors.
#. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
# bspc config normal_border_color "$color1"
# bspc config active_border_color "$color2"
# bspc config focused_border_color "$color15"
# bspc config presel_feedback_color "$color1"

bspc config focused_border_color "#03fc62"
bspc config normal_border_color "#ed8796"
bspc config active_border_color "#cba6f7"
bspc config presel_feedback_color "#a6d189"

bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config paddingless_monocle true
bspc config single_monocle false
bspc config focus_follows_pointer true

bspc rule -a LibreWolf desktop='^3' follow=on focus=on
bspc rule -a Nemo desktop='^3' follow=on focus=on
bspc rule -a discord desktop='^6' follow=on focus=on
bspc rule -a geany desktop='^4' follow=on focus=on
bspc rule -a qBittorrent desktop='^5' follow=on focus=on

#bspc rule -a Vivaldi desktop='^2' state=floating follow=on monitor=HDMI-1

# StartUP Apps
ibus-daemon -drx &
qbittorrent &
sxhkd &
discord &
flameshot &
.config/bspwm/scripts/vivaldi.sh &

# Picom
picom --experimental-backends --config $HOME/.config/bspwm/picom/picom.conf &

# Polkit
/usr/bin/lxpolkit &

# Wallpaper
feh --bg-scale ~/.config/bspwm/wallpapers/landmark.jpg &

# Notification
dunst &

# Cursor
xsetroot -cursor_name left_ptr &

# Polybar
.config/bspwm/polybar/launch.sh &

# Java Apps
export _JAVA_AWT_WM_NONREPARENTING=1 &

# Display sleep = off
xset -dpms &
xset s off &

# Number Lock
numlockx &

# auto mount USB
if ! pgrep -x "udiskie" >/dev/null; then
	udiskie -t &
fi

# multi-monitor
.screenlayout/multi-monitor.sh &
